### ISSUE TITLE
Skipped copy as --dry-run is set

### ISSUE THREAD

**Issue by pohq** [jcwillox/hassio-rclone-backup#102]
### The problem

I have set up Rclone on home assistant and all seems to be working. BUT when it comes to the backup time it says

Skipped copy as --dry-run is set

Nowhere is dry run set in the config in fact I have applied dry run false to the config yaml but still it persists

Any help would be appriciated! my Config Yaml

### What version of Rclone Backup has the issue?

Current version: 3.3.3

### What version of Home Assistant are you running?

2025.1.2

### What type of installation are you running?

Home Assistant Core

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.12.3

### Example YAML snippet

```yml
- name: Sync Daily Backups
  schedule: 45 6 * * *
  command: sync
  sources:
    - /backup
  destination: Dropbox:/habackups
  include: []
  exclude: []
  flags: {}
  dry_run: false
  extra_args:
    - "--no-dry-run"
```
