### ISSUE TITLE
Add date to the backup name

### ISSUE THREAD

**Issue by davidesolito** [jcwillox/hassio-rclone-backup#105]
### The problem

Hi, currently my backups are saved with the name: Automatic_backup_2025-1-3. I would like to add the time to this as well. Is it possible? How can I achieve this?

### What version of Rclone Backup has the issue?

 3.3.4

### What version of Home Assistant are you running?

2025.1.3

### What type of installation are you running?

Home Assistant Supervised

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.12.3

### Example YAML snippet

```yml
- name: Sync Daily Backups
  schedule: 45 05 * * *
  command: sync
  sources:
    - /backup
  destination: nextcloud:/Locale/Backup/Home Assistant
  include:
    - Automatic_backup*
  exclude: []
```

### Anything in the logs that might be useful for us?

```python3

```
