### ISSUE TITLE
friendly name

### ISSUE THREAD

**Issue by tangli159** [jcwillox/hassio-rclone-backup#14]
Hello,I've noticed the option:no_unrename.

> no_unrename
> Prevents renaming backups back to their original name, with this enabled the backup files will be renamed to use their friendly name and this will persist on disk.
> Note: this option can apparently cause issues with restoring backups but won't affect the actual integrity of the snapshots, exercise caution when using it.

It works well,but the problem is that my backup names always are Chinese. I don't want to change the names to English.

The friendly names show Chinese correctly in hassio backups,but in my cloud storage they show pinyin.
example：
每周自动备份:2022年03月06日21:59:52,Sunday → Mei-Zhou-Zi-Dong-Bei-Fen-2022Nian-03Yue-06Ri-215952Sunday.tar

How to solve it?

I use your autobackup to backup and this program to upload.
my config is
```
jobs:
  - name: Sync Daily Backups
    schedule: 5 0 * * *
    command: sync
    sources:
      - /backup
    destination: NAS:/HassioBackup
    include: []
    exclude: []
    flags: {}
dry_run: false
config_path: /config/rclone.conf
no_unrename: true
```
