### ISSUE TITLE
Help connecting rclone extension with autobackup

### ISSUE THREAD

**Issue by nchieffo** [jcwillox/hassio-rclone-backup#19]
Hello,
I'm a new user and I have troubles understanding how to properly use this extension with the autobackup extension.
In the rclone configuration I can see the option to include only some files from the /backup folder, but my backup file names are only containing random characters, even if I used the 'name' option.
I think I understand that the reason is due to the docker installation that can't access /backup folder directly (I'm using home assistant OS)

Do you have any suggestions?

Thanks for your help

current way I call autobackup
```
    - service: auto_backup.backup
      data:
        exclude_addons:
          - core_mariadb
        exclude_folders:
          - media
        password: !secret backup_pass
        keep_days: 7
        name: auto_daily_{{ now().strftime('%Y-%m-%d') }}
```

**Comment by jcwillox** [comment]
On the filesystem, your backups are named with their slugs e.g. `c1d7fdeb.tar`, however, this addon will temporarily rename the backups to use the friendly name you gave them. That name is what you want to match, the snippet below should include all your daily backups.

```yaml
jobs:
  - name: Sync Daily Backups
    # ...
    include:
      - auto_daily_*
```

> but my backup file names are only containing random characters, even if I used the 'name' option

Yeah, exactly Auto Backup cannot control or change the name of the backup on the filesystem as it doesn't have access, and Home Assistant chooses to name backups like that, the actual name is stored in a `backup.json` file inside the backup.
