### ISSUE TITLE
WebUI returns 404 when downloading file

### ISSUE THREAD

**Issue by FrankZZ** [jcwillox/hassio-rclone-backup#22]
### The problem

In the Explorer view of the Web UI I can successfully upload files and I see them in my onedrive. 
However, when I click the download button of one of those files through the WebUI -> Explorer I see a HTTP/404 response for the GET request of the file.

request path (ignore the redacted part. the real value is the same as for example "List files" requests that succeed):
```
/api/hassio_ingress/*REDACTED*/[hassbackup:]/scan-1.svg
```

I am using onedrive as remote (wrapped in a crypt remove but I also tried without crypt, same issue)

### What version of Rclone Backup has the issue?

3.0.0

### What version of Home Assistant are you running?

2022.9.6

### What type of installation are you running?

Home Assistant Supervised

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2022.09.1

### Example YAML snippet

```yml
jobs:
  - name: Sync Daily Backups
    schedule: 10 4 * * *
    command: sync
    sources:
      - /backup
    destination: "hassbackup:"
    include: []
    exclude: []
    flags: {}
dry_run: false
config_path: /config/rclone.conf
log_level: debug
rclone_config: >
  [onedrive]
  type = onedrive
  token = {"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"xxx"}
  drive_id = xxx
  drive_type = personal

  [hassbackup]
  type = crypt
  remote = onedrive:backup/ha
  filename_encryption = off
  directory_name_encryption = false
  password = xxx
  password2 = xxx
```
