### ISSUE TITLE
[FR]: Add the option of mount folders

### ISSUE THREAD

**Issue by McGiverGim** [jcwillox/hassio-rclone-backup#27]
### Is your feature request related to a problem? Please describe.

I want to upload to Google Drive images/videos of my cameras as soon as they are taken. 
I want to mount the folder where the camera saves the files to a Google Drive folder.

### Describe the solution you'd like

The possibility to use the mount command of rclone.

### Describe alternatives you've considered

I tried several ways to upload files to Google Drive from Home Assistant without luck.

### Additional context

None. Thanks!

**Comment by jcwillox** [comment]
I think you might be able to do that via the web UI, but it probably won't survive restarts.
It might also be possible to do it via a job at startup (e.g. a job without a schedule), but I think it might block other jobs from running, so perhaps an option to make a startup job run in the background is needed.

**Comment by jcwillox** [comment]
Tested out mounting a directory with the following job config

```yaml
- command: mount
  name: Mount Backups
  source: hassbackup:/
  extra_flags:
    - "--vfs-cache-mode=writes"
    - /share/google
```

Fails because fuse is missing, so somehow have to get that working inside the docker container, hopefully I can just install that into the container 🤞
