### ISSUE TITLE
Keep x files

### ISSUE THREAD

**Issue by poudenes** [jcwillox/hassio-rclone-backup#31]
### Is your feature request related to a problem? Please describe.

not related to a problem

### Describe the solution you'd like

Would be nice to add a extra option in jobs config:
```
keep_files: 3 # or what you want
```
I created backups with date. And want keep last 3 files.

or in this part
```
- name: Daily Sync Backup
  schedule: 33 10 * * *
  command: sync
  sources:
    - /backup
  destination: minio:habackup
  keep_files: 3
  config_path: /config/rclone.conf
```

On my VPS site I use clone also to copy backups to minio and use this command to remove files older then:

```
rclone delete --min-age 3d minio:habackup 
```

or in the config.conf file hardcoded for every job.

### Describe alternatives you've considered

remove files manual from the destination location.

**Comment by poudenes** [comment]
Went into the docker and created in '/root/.config/rclone' the 'rclone.conf' file also
```
root@19a172aa-rclone-backup:/root/.config/rclone$ rclone delete --min-age 3d minio:habackup --dry-run
2023/02/25 12:54:34 NOTICE: .samba_backup.sensor: Skipped delete as --dry-run is set (size 245)
2023/02/25 12:54:34 NOTICE: Backup-HA-2023-2-5-2023-02-22_08_30.tar: Skipped delete as --dry-run is set (size 362.383Mi)
root@19a172aa-rclone-backup:/root/.config/rclone$ 
```
The command rclone delete is working :). Did a --dry-run for testing.

**Comment by poudenes** [comment]
Solved. Add keep_days in "hass-auto-backup" add-on.

https://github.com/jcwillox/hass-auto-backup

**Comment by jcwillox** [comment]
Yeah sorry I've been quite busy the past few weeks, but yes thats the way to go. You could also possibly use `rclone delete` as a scheduled job.

**Comment by poudenes** [comment]
> Yeah sorry I've been quite busy the past few weeks, but yes thats the way to go. You could also possibly use `rclone delete` as a scheduled job.

Thats an option. But still how do I add that I want keep x days?

**Comment by poudenes** [comment]
It will be something like this then?
```
- name: Delete partial backups older then 3 days
  schedule: 0 23 * * * 
  command: delete --min-age 3d
  sources:
    - /share/backup/partial
  destination: sftp:ha/full
```

**Comment by jcwillox** [comment]
Yeah that'd be the way, except you'd need to use `flags`/`extra_flags` for the arguments

```yaml
- name: Delete partial backups older then 3 days
  schedule: 0 23 * * * 
  command: delete
  extra_flags:
    - "--min-age=3d"
  # you could even use include to target backups by name
  include:
      - DailyBackup*
  sources:
    - /share/backup/partial
  destination: minio:ha/partial
```

**Comment by Adrianni** [comment]
@jcwillox,

I'm using your suggestion in previous post:
`- name: Delete partial backups older then 6 days
   schedule: 29 * * * *
  command: delete
  extra_flags:
    - "--min-age=6d"
  destination: JottaCloud:/Backup/Home Assistant
  sources:
    - /backup
`

But this gives the following error: 
`Command delete needs 1 arguments maximum: you provided 2 non flag arguments: ["/backup" "JottaCloud:/Backup/Home Assistant"]
[2024-07-16] [13:29:00] [ERROR]: failed to run rclone command: exit status 1`

If i remove the sources argument, it fails to start the addon due to the missing sources. Any suggestion how to overcome this?

**Comment by scharmach** [comment]
@Adrianni I've just installed the addon and stumbled across this issue. When I tried the code above, I got the same error.

I'll probably fine-tune this further, but this combination works for me:

```
- name: Alte Backups nach 14 Tagen löschen
  schedule: 0 0 * * *
  command: delete
  extra_flags:
    - "--min-age=14d"
  sources:
    - /backup
- name: Backups zu Nextcloud synchronisieren
  schedule: 30 3 * * *
  command: sync
  sources:
    - /backup
  destination: remote:/Backups/Home Assistant
```

Basically, I've set no `destination` for the `delete`-command.
