### ISSUE TITLE
Local download of Google Drive data

### ISSUE THREAD

**Issue by GMCfourX4** [jcwillox/hassio-rclone-backup#52]
### The problem

Thank you for all of your work on the add-on.
I was able to get the add-on installed and connected to Google Drive. I can list the files that I am looking for in the browser. What I would like to do is to use the rclone sync functionality to bring a copy of my files onto the Home Assistant system so that I can access them from the 'Media' section of Home Assistant. When I try to setup a sync to a path such as /media/GoogleDrive I get errors that the location is read-only. I have tried a drive mount, but all of the ways I have tried to do that result in a 500 error.

### What version of Rclone Backup has the issue?

3.1.0

### What version of Home Assistant are you running?

2021.3.1

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.03.0

### Example YAML snippet

```yml
- name: Sync Media
  schedule: 1 * * * *
  command: sync
  sources:
    - "GoogleDrive:"
  destination: /media/gdrive
```
