### ISSUE TITLE
[FR]: Clean up remote backups

### ISSUE THREAD

**Issue by tbelway** [jcwillox/hassio-rclone-backup#84]
### Is your feature request related to a problem? Please describe.

The ability for rclone to delete on the remote is already baked in. However, the regex used to validate the config prevents deleting on the remote, citing a source is required.

### Describe the solution you'd like

Remove the source requirement on delete command.

**Comment by balk77** [comment]
I was also thinking that rclone was able to keep two folders in sync. I prefer to delete my hourly backups automatically. Am I overseeing some option?

**Comment by niels-db** [comment]
When configuring a `rclone delete` command with this plugin you have to set the remote as source and not as destination.
So you have to fill in the remote as source and leave destination blank. There's an example job "Prune Old Backups" available in the readme that you can use as a reference.

```yaml
jobs:
  - name: Sync Daily Backups
    schedule: 10 4 * * *
    command: sync
    sources:
      - /backup
    destination: 'hassbackup:'
    include:
      - DailyBackup*
    exclude: []
    # we can also disable google drive trash using flags
    flags:
      drive-use-trash: false
  # In case we also want to prune backups that are older than 14 days
  - name: Prune Old Backups
    schedule: 10 5 * * *
    command: delete
    sources:
      - 'hassbackup:'
    flags:
      min-age: 14d
dry_run: false
config_path: /homeassistant/rclone.conf
```
