### ISSUE TITLE
Test run

### ISSUE THREAD

**Issue by marcschumacher** [jcwillox/hassio-rclone-backup#87]
Is it possible to have a test run for my job without having to specify a specific time and wait for this? It would be cool to be able to just trigger it on demand and see the output in the logs.

**Comment by jcwillox** [comment]
Yep, simply don't include a schedule and the job will run on startup, so each time you save your configuration and restart the container it will run the job.

I have one that just prints out my backups on the remote, so I can see that the connection is working
```yaml
- command: ls
  name: List Backups
  source: "hassbackup:"
  flags:
    human-readable: true
```
